version: "3.7"


  # app:
  #   build:
  #     context: ./WebGoat
  #     dockerfile: Dockerfile
  #   image: webgoat/webgoat-8.0
  #   volumes:
  #     - .:/home/webgoat/.webgoat
  #   ports: 
  #     - "1234:8080"
  #     - "5678:9090"
  #   networks:
  #     - app-network


services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp-server
    container_name: myapp-node-server
    command: npm start
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - mongo
      - zap
    env_file: ./config/default.json
    environment:
      - MONGO_URI=mongodb://host.docker.internal:27017/secassess
      - ZAP_PROXY=http://zap:8081
      - IS_DOCKER=true
    networks:
      - app-network
  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

  client:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    image: myapp-client
    container_name: myapp-react-client
    command: npm start
    volumes:
      - ./react-app/:/usr/src/app/react-app
      - /usr/src/app/react-app/node_modules
    depends_on:
      - server
    env_file: ./react-app/src/config.json
    environment:
      - REACT_APP_API_ENDPOINT=http://localhost:3001
    ports:
      - "3000:3000"
    networks:
      - app-network

  zap:
    image: owasp/zap2docker-stable:2.9.0
    container_name: zap
    command: zap.sh -daemon -port 8081 -host 0.0.0.0 -config api.disablekey=true -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true
    ports:
      - "8081:8080"
    networks:
      - app-network

  # Selenium Hub to control browsers
  selenium-hub:
    image: selenium/hub:3.141.59
    container_name: selenium-hub
    ports:
      - 4444:4444
    networks:
      - app-network

  chrome:
    image: selenium/node-chrome-debug:3.141.59
    container_name: chrome-node
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 5900:5900
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    networks:
      - app-network

  firefox:
    image: selenium/node-firefox-debug:3.141.59
    container_name: firefox-node
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 5901:5900
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local
