module.exports = {
  1: "Insufficient Authentication",
  2: "Insufficient Authorization",
  3: "Integer Overflows",
  4: "Insufficient Transport Layer Protection",
  5: "Remote File Inclusion",
  6: "Format String",
  7: "Buffer Overflow",
  8: "Cross-site Scripting",
  9: "Cross-site Request Forgery",
  10: "Denial of Service",
  11: "Brute Force",
  12: "Content Spoofing",
  13: "Information Leakage",
  14: "Server Misconfiguration",
  15: "Application Misconfiguration",
  16: "Directory Indexing",
  17: "Improper Filesystem Permissions",
  18: "Credential/Session Prediction",
  19: "SQL Injection",
  20: "Improper Input Handling",
  21: "Insufficient Anti-Automation",
  22: "Improper Output Handling",
  23: "XML Injection",
  24: "HTTP Request Splitting",
  25: "HTTP Response Splitting",
  26: "HTTP Request Smuggling",
  27: "HTTP Response Smuggling",
  28: "Null Byte Injection",
  29: "LDAP Injection",
  30: "Mail Command Injection",
  31: "OS Commanding",
  32: "Routing Detour",
  33: "Path Traversal",
  34: "Predictable Resource Location",
  35: "SOAP Array Abuse",
  36: "SSI Injection",
  37: "Session Fixation",
  38: "URl Redirector Abuse",
  39: "XPath Injection",
  40: "Insufficient Process Validation",
  41: "XML Attribute Blowup",
  42: "Abuse of Functionality",
  43: "XML External Entities",
  44: "XML Entity Expansion",
  45: "Fingerprinting",
  46: "XQuery Injection",
  47: "Insufficient Session Expiration",
  48: "Insecure Indexing",
  49: "Insufficient Password Recovery",
  50: "Insufficient Data Protection",
};
